version: "3.9"

services:

  microservicio:
    build: .
    container_name: microservicio-devops

    ports:
      - "5000:5000"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - devops-network

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - microservicio

    networks:
      - devops-network

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards-json:/etc/grafana/provisioning/dashboards-json

    depends_on:
      - prometheus

    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge