{
 "title": "Dashboard DevOps",
 "tags": [ "devops" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Peticiones Totales",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "peticiones_totales_total" }
   ]
  },
  {
   "title": "Errores Totales",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "errores_totales_total" }
   ]
  },
  {
   "title": "Health Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "health_checks_totales_total" }
   ]
  },
  {
   "title": "Tiempo de Respuesta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(tiempo_respuesta_segundos_sum[1m]) / rate(tiempo_respuesta_segundos_count[1m])"
    }
   ]
  }
 ]
}